# Generated by Django 3.0.6 on 2020-06-18 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=20)),
                ('nome_fantasia', models.CharField(max_length=50)),
                ('razao_social', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
                ('dominio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoDeTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyticx.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioVsRelatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyticx.Empresa')),
                ('grupo_de_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyticx.GrupoDeTrabalho')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyticx.Empresa')),
                ('grupo_de_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyticx.GrupoDeTrabalho')),
            ],
        ),
    ]
